import type { SqlQueryOutput } from '@prisma/generator';
import ts from 'typescript';
import type { PrismaJsonTypesGeneratorConfig } from '../util/config';
import { createType } from '../util/create-signature';
import type { DeclarationWriter } from '../util/declaration-writer';

/** A map from column name to field documentation for JSON fields. */
export type ColumnAnnotationMap = Map<string, string | undefined>;

/**
 * Handles a TypedSQL query file by replacing JSON column types with annotated types.
 *
 * TypedSQL files are TypeScript modules generated by Prisma that represent typed SQL
 * queries. Each file exports a factory function and a namespace with `Parameters` and
 * `Result` types. This handler replaces `$runtime.JsonValue` types in the `Result` type
 * with user-annotated types from the Prisma schema.
 */
export function handleTypedSqlFile(
  tsSource: ts.SourceFile,
  writer: DeclarationWriter,
  query: SqlQueryOutput,
  columnAnnotationMap: ColumnAnnotationMap,
  config: PrismaJsonTypesGeneratorConfig
) {
  // Only process json and json-array typed columns
  const jsonColumns = query.resultColumns.filter(
    (col) => col.typ === 'json' || col.typ === 'json-array'
  );

  if (jsonColumns.length === 0) return;

  // Build a map of column name → replacement info
  const columnsToReplace = new Map<
    string,
    { newType: string; nullable: boolean; isArray: boolean }
  >();

  for (const col of jsonColumns) {
    const documentation = columnAnnotationMap.get(col.name);

    // No annotation and allowAny is set — skip replacing
    if (!documentation && config.allowAny) continue;

    const newType = createType(documentation, config);
    columnsToReplace.set(col.name, {
      newType,
      nullable: col.nullable,
      isArray: col.typ === 'json-array'
    });
  }

  if (columnsToReplace.size === 0) return;

  // Traverse the top-level namespace declaration matching the query name
  tsSource.forEachChild((child) => {
    if (child.kind !== ts.SyntaxKind.ModuleDeclaration) return;

    const ns = child as ts.ModuleDeclaration;
    if (ns.name.getText() !== query.name) return;

    const body = ns.body;
    if (!body || body.kind !== ts.SyntaxKind.ModuleBlock) return;

    for (const stmt of (body as ts.ModuleBlock).statements) {
      if (stmt.kind !== ts.SyntaxKind.TypeAliasDeclaration) continue;

      const typeAlias = stmt as ts.TypeAliasDeclaration;
      if (typeAlias.name.getText() !== 'Result') continue;
      if (typeAlias.type.kind !== ts.SyntaxKind.TypeLiteral) continue;

      const typeLiteral = typeAlias.type as ts.TypeLiteralNode;

      for (const member of typeLiteral.members) {
        if (member.kind !== ts.SyntaxKind.PropertySignature) continue;

        const prop = member as ts.PropertySignature;
        const propName = prop.name?.getText();

        if (!propName || !columnsToReplace.has(propName)) continue;

        const { newType, nullable, isArray } = columnsToReplace.get(propName)!;
        const typeNode = prop.type;

        if (!typeNode) continue;

        let replacement: string;
        if (isArray) {
          replacement = `${newType}[]`;
        } else if (nullable) {
          replacement = `${newType} | null`;
        } else {
          replacement = newType;
        }

        // Use getStart() (not pos) to exclude leading trivia so the
        // space between the colon and the type is preserved.
        writer.replace(typeNode.getStart(tsSource), typeNode.end, replacement);
      }
    }
  });
}
