export const JSON_REGEX = /^\s*\[(.*?)\]/m;

/**
 * A list of regexes to match all types and subtypes generated by prisma for a specific model
 */
export function regexForPrismaType(name: string) {
  return [
    new RegExp(`^${name}CountAggregate$`, 'm'),
    // new RegExp(`^${name}CountAggregateInputType$`, 'm'), `true` fields
    // new RegExp(`^${name}CountAggregateOutputType$`, 'm'), `number` fields
    // new RegExp(`^${name}CountOrderByAggregateInput$`, 'm'), `SortOrder` fields

    new RegExp(`^${name}Group$`, 'm'),
    new RegExp(`^${name}GroupByOutputType$`, 'm'),

    // new RegExp(`^${name}Select$`, 'm'), boolean type
    new RegExp(`^${name}WhereInput$`, 'm'),
    new RegExp(`^${name}WhereUniqueInput$`, 'm'),

    // new RegExp(`^${name}OrderByWithRelationInput$`, 'm'), `SortOrder` fields
    // new RegExp(`^${name}OrderByWithAggregationInput$`, 'm'), `SortOrder` fields

    new RegExp(`^${name}ScalarWhere$`, 'm'),
    new RegExp(`^${name}ScalarWhereInput$`, 'm'),
    new RegExp(`^${name}ScalarWhereWithAggregatesInput$`, 'm'),

    new RegExp(`^${name}(?:Unchecked)?CreateInput$`, 'm'),
    new RegExp(`^${name}(?:Unchecked)?CreateManyInput$`, 'm'),
    new RegExp(`^${name}(?:Unchecked)?CreateWithout(?:\\w+?)Input$`, 'm'),
    new RegExp(`^${name}(?:Unchecked)?CreateMany(?:\\w+?)Input$`, 'm'),

    ...regexForPrismaUpdateType(name)
  ];
}

export function regexForPrismaUpdateType(name: string) {
  return [
    new RegExp(`^${name}(?:Unchecked)?UpdateInput$`, 'm'),
    new RegExp(`^${name}(?:Unchecked)?UpdateManyInput$`, 'm'),
    new RegExp(`^${name}(?:Unchecked)?UpdateManyMutationInput$`, 'm'),
    new RegExp(`^${name}(?:Unchecked)?UpdateWithout(?:\\w+?)Input$`, 'm')
  ];
}
